name: Waste Management System CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    
    - name: Prepare GitHub Pages Deploy
      run: |
        mkdir -p gh-pages
        cp -r web/* gh-pages/
        echo "waste-management.razee4315.github.io" > gh-pages/CNAME
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./gh-pages
        publish_branch: gh-pages
        full_commit_message: Deploy web application
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
    
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          web/*
        tag_name: v1.0.0-${{ github.sha }}
        body: |
          ## Waste Management System Release
          
          ### Deployment Details
          - Web Application deployed to GitHub Pages
          - Full source code included
          
          ### Changelog
          - Automated web deployment
          - Latest web interface updates
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
